name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Style and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare Python environment
        run: pip install --upgrade pip tox

      - name: Lint
        run: tox -e lint

  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare Python environment
        run: pip install --upgrade pip tox

      - name: Build documentation
        run: tox -e docs

      - uses: actions/upload-artifact@v3
        with:
          name: qiskit-qasm2-docs
          path: |
            ./docs/_build/html/*
            !**/.doctrees
            !**/.buildinfo
          if-no-files-found: error

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Just using minimum and maximum to avoid exploding the matrix.
        python-version: ['3.8', '3.11']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare Python environment
        run: pip install --upgrade pip tox

      - name: Run tests
        run: |
          set -e
          py=${{ matrix.python-version }}
          tox -e py${py/./}

  coverage:
    name: Coverage data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: default
          components: llvm-tools-preview

      - name: Install grcov
        run: cargo install grcov

      - name: Install lcov
        run: sudo apt-get install lcov

      - name: Prepare Python environment
        run: pip install --upgrade pip tox

      - name: Run tests
        run: tox -e coverage

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.info

  deploy-docs:
    name: Deploy documentation
    runs-on: ubuntu-latest
    needs: [docs]
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: qiskit-qasm2-docs
          path: deploy

      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GHPAGES_DEPLOY_TOKEN }}
          repository-name: jakelishman/jakelishman.github.io
          branch: main
          folder: deploy
          target-folder: qiskit-qasm2
