name: Deploy Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy_sdist:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Install build dependencies
        run: python -I -m pip install -U pip wheel build

      - name: Build sdist tarball
        run: python -I -m build --sdist .

      - name: Verify version information
        run: |
          set -e
          # Extract version information from the built sdist.
          sdist_version=$(ls -1 ./dist | sed 's/qiskit_qasm2-\(.*\)\.tar\.gz/\1/')
          # Extract the version information from the end of the tag.
          tag_version=${GITHUB_REF#refs/tags/v}
          if [[ "$tag_version" != "$wheel_version" ]]; then
            echo "Version mismatch: tag says '$tag_version', wheel says '$wheel_version'" >&2
            exit 1
          fi

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.JAKELISHMAN_PYPI_TOKEN }}
        run: |
          set -e
          python -I -m pip install -U twine
          twine upload ./dist/*.tar.gz

  deploy:
    name: Deploy to PyPI on ${{ matrix.os }}
    # We do the version checking in the sdist deployment, so gate the wheel builds on that to avoid needing to
    # check everywhere.
    needs: deploy_sdist
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Install build dependencies
        run: |
            set -e
            python -I -m pip install -U pip wheel
            python -I -m pip install -U 'cibuildwheel~=2.11.0' twine

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse .

      - name: Build package
        run: |
          set -e
          python3 -mvenv .venv
          source .venv/bin/activate

          pip install -U pip wheel build
          python -m build --sdist --wheel

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.JAKELISHMAN_PYPI_TOKEN }}
        run: |
          set -e
          source .venv/bin/activate

          python3 -mpip install -U twine
          twine upload ./wheelhouse/*.whl
